// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"e.coding.net/aliens/aliensboot_testserver/module/room/core"
	"e.coding.net/aliens/aliensboot_testserver/protocol"
)




//
func handleBroadcastViewer(authID int64, gateID string, request *protocol.BroadcastViewer) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	push := &protocol.Response{Room: &protocol.Response_BroadcastViewerRet{BroadcastViewerRet: &protocol.BroadcastViewerRet{
		Data:request.GetData(),
	}}}
	room.BroadcastViewer(push)
}
