// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"e.coding.net/aliens/aliensboot_testserver/module/room/core"
	"e.coding.net/aliens/aliensboot_testserver/protocol"
)


//
func handleUpdateBigoData(authID int64, gateID string, request *protocol.UpdateBigoData) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	room.AcceptPlayerMessage(authID, request, nil)
}
