// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"e.coding.net/aliens/aliensboot_testserver/module/room/core"
	"e.coding.net/aliens/aliensboot_testserver/protocol"
)


//
func handleRespondJoinGame(authID int64, gateID string, request *protocol.RespondJoinGame) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	room.JoinGame(authID)
}
