// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"e.coding.net/aliens/aliensboot_testserver/module/room/core"
	"e.coding.net/aliens/aliensboot_testserver/protocol"
)


//
func handleOnPlayerStateChange(authID int64, gateID string, request *protocol.OnPlayerStateChange, response *protocol.OnPlayerStateChangeRet) {
	response.Code =  core.RoomManager.ChangePlayerState(authID, request.GetPlayerID(), request.GetState())
}


