// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import "e.coding.net/aliens/aliensboot_testserver/protocol"




//
func handlePreJoinGame(authID int64, gateID string, request *protocol.PreJoinGame) {

}
