// Code generated by aliensbot. DO NOT EDIT.
// source: gate_interface.proto
package service

import "e.coding.net/aliens/aliensboot_testserver/protocol"


//
func handleHeartBeat(request *protocol.HeartBeat) {

}
