// Code generated by aliensbot. DO NOT EDIT.
// source: scene_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot/exception"
	"github.com/KylinHe/aliensboot/mmo"
	"github.com/KylinHe/aliensboot/mmo/core"
	entity2 "e.coding.net/aliens/aliensboot_testserver/module/scene/entity"
	"e.coding.net/aliens/aliensboot_testserver/protocol"
)

//
func handleEntityCall(authID int64, gateID string, request *protocol.EntityCall) {
	entity, err := mmo.RemoteEntityCall(entity2.GetPlayerID(authID), core.EntityID(request.GetEntityID()), request.GetMethod(), request.GetArgs())
	if entity == nil {
		exception.GameException1(protocol.Code_entityNotFound, err)
	}
}
