// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"aliens/testserver/module/room/core"
	"aliens/testserver/protocol"
)

//
func handleRequestJoinGame(authID int64, gateID string, request *protocol.RequestJoinGame) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	room.RequestJoinGame(authID)
}
