// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: scene.proto

package scene

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Vector struct {
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{0} }

func (m *Vector) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Entity struct {
	Id        int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position  *Vector `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Direction *Vector `protobuf:"bytes,3,opt,name=direction" json:"direction,omitempty"`
	Data      string  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{1} }

func (m *Entity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetPosition() *Vector {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Entity) GetDirection() *Vector {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *Entity) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SpaceEnter struct {
	SpaceID   int32   `protobuf:"varint,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	Position  *Vector `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	Direction *Vector `protobuf:"bytes,3,opt,name=direction" json:"direction,omitempty"`
}

func (m *SpaceEnter) Reset()                    { *m = SpaceEnter{} }
func (m *SpaceEnter) String() string            { return proto.CompactTextString(m) }
func (*SpaceEnter) ProtoMessage()               {}
func (*SpaceEnter) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{2} }

func (m *SpaceEnter) GetSpaceID() int32 {
	if m != nil {
		return m.SpaceID
	}
	return 0
}

func (m *SpaceEnter) GetPosition() *Vector {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *SpaceEnter) GetDirection() *Vector {
	if m != nil {
		return m.Direction
	}
	return nil
}

type SpaceEnterRet struct {
	EntityID int32 `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
}

func (m *SpaceEnterRet) Reset()                    { *m = SpaceEnterRet{} }
func (m *SpaceEnterRet) String() string            { return proto.CompactTextString(m) }
func (*SpaceEnterRet) ProtoMessage()               {}
func (*SpaceEnterRet) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{3} }

func (m *SpaceEnterRet) GetEntityID() int32 {
	if m != nil {
		return m.EntityID
	}
	return 0
}

type SpaceMove struct {
	SpaceID   int32   `protobuf:"varint,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	EntityID  int32   `protobuf:"varint,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Position  *Vector `protobuf:"bytes,3,opt,name=position" json:"position,omitempty"`
	Direction *Vector `protobuf:"bytes,4,opt,name=direction" json:"direction,omitempty"`
}

func (m *SpaceMove) Reset()                    { *m = SpaceMove{} }
func (m *SpaceMove) String() string            { return proto.CompactTextString(m) }
func (*SpaceMove) ProtoMessage()               {}
func (*SpaceMove) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{4} }

func (m *SpaceMove) GetSpaceID() int32 {
	if m != nil {
		return m.SpaceID
	}
	return 0
}

func (m *SpaceMove) GetEntityID() int32 {
	if m != nil {
		return m.EntityID
	}
	return 0
}

func (m *SpaceMove) GetPosition() *Vector {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *SpaceMove) GetDirection() *Vector {
	if m != nil {
		return m.Direction
	}
	return nil
}

type SpaceMoveRet struct {
}

func (m *SpaceMoveRet) Reset()                    { *m = SpaceMoveRet{} }
func (m *SpaceMoveRet) String() string            { return proto.CompactTextString(m) }
func (*SpaceMoveRet) ProtoMessage()               {}
func (*SpaceMoveRet) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{5} }

type SpaceLeave struct {
	SpaceID  int32 `protobuf:"varint,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	EntityID int32 `protobuf:"varint,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
}

func (m *SpaceLeave) Reset()                    { *m = SpaceLeave{} }
func (m *SpaceLeave) String() string            { return proto.CompactTextString(m) }
func (*SpaceLeave) ProtoMessage()               {}
func (*SpaceLeave) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{6} }

func (m *SpaceLeave) GetSpaceID() int32 {
	if m != nil {
		return m.SpaceID
	}
	return 0
}

func (m *SpaceLeave) GetEntityID() int32 {
	if m != nil {
		return m.EntityID
	}
	return 0
}

type SpaceLeaveRet struct {
}

func (m *SpaceLeaveRet) Reset()                    { *m = SpaceLeaveRet{} }
func (m *SpaceLeaveRet) String() string            { return proto.CompactTextString(m) }
func (*SpaceLeaveRet) ProtoMessage()               {}
func (*SpaceLeaveRet) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{7} }

type GetState struct {
	SpaceID  int32 `protobuf:"varint,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	EntityID int32 `protobuf:"varint,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
}

func (m *GetState) Reset()                    { *m = GetState{} }
func (m *GetState) String() string            { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()               {}
func (*GetState) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{8} }

func (m *GetState) GetSpaceID() int32 {
	if m != nil {
		return m.SpaceID
	}
	return 0
}

func (m *GetState) GetEntityID() int32 {
	if m != nil {
		return m.EntityID
	}
	return 0
}

type GetStateRet struct {
	Neighbors []*Entity `protobuf:"bytes,1,rep,name=neighbors" json:"neighbors,omitempty"`
}

func (m *GetStateRet) Reset()                    { *m = GetStateRet{} }
func (m *GetStateRet) String() string            { return proto.CompactTextString(m) }
func (*GetStateRet) ProtoMessage()               {}
func (*GetStateRet) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{9} }

func (m *GetStateRet) GetNeighbors() []*Entity {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

// 场景信息变更推送
type SpacePush struct {
	Neighbors []*Entity `protobuf:"bytes,1,rep,name=neighbors" json:"neighbors,omitempty"`
}

func (m *SpacePush) Reset()                    { *m = SpacePush{} }
func (m *SpacePush) String() string            { return proto.CompactTextString(m) }
func (*SpacePush) ProtoMessage()               {}
func (*SpacePush) Descriptor() ([]byte, []int) { return fileDescriptorScene, []int{10} }

func (m *SpacePush) GetNeighbors() []*Entity {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector)(nil), "Vector")
	proto.RegisterType((*Entity)(nil), "Entity")
	proto.RegisterType((*SpaceEnter)(nil), "space_enter")
	proto.RegisterType((*SpaceEnterRet)(nil), "space_enter_ret")
	proto.RegisterType((*SpaceMove)(nil), "space_move")
	proto.RegisterType((*SpaceMoveRet)(nil), "space_move_ret")
	proto.RegisterType((*SpaceLeave)(nil), "space_leave")
	proto.RegisterType((*SpaceLeaveRet)(nil), "space_leave_ret")
	proto.RegisterType((*GetState)(nil), "get_state")
	proto.RegisterType((*GetStateRet)(nil), "get_state_ret")
	proto.RegisterType((*SpacePush)(nil), "space_push")
}

func init() { proto.RegisterFile("scene.proto", fileDescriptorScene) }

var fileDescriptorScene = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x93, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0x24, 0xa4, 0xcd, 0x05, 0x0a, 0x78, 0xb2, 0x98, 0x22, 0xa3, 0x4a, 0x5d, 0xe8,
	0xd0, 0x4a, 0xec, 0x08, 0x18, 0x58, 0x33, 0xb0, 0x46, 0x69, 0x72, 0x6a, 0x2d, 0x41, 0x1c, 0xd9,
	0x06, 0x25, 0xfd, 0x11, 0xfc, 0x66, 0x14, 0x87, 0x24, 0xcd, 0x00, 0xaa, 0x2a, 0x36, 0x3f, 0xdd,
	0xdd, 0xbb, 0xcf, 0x4f, 0x36, 0x84, 0x3a, 0xc3, 0x02, 0x97, 0xa5, 0x92, 0x46, 0xf2, 0x15, 0xf8,
	0xaf, 0x98, 0x19, 0xa9, 0xe8, 0x39, 0x90, 0x8a, 0x91, 0x88, 0x2c, 0x9c, 0x98, 0x54, 0x8d, 0xaa,
	0x99, 0xd3, 0xaa, 0xba, 0x51, 0x7b, 0xe6, 0xb6, 0x6a, 0xcf, 0x2b, 0xf0, 0x9f, 0x0b, 0x23, 0x4c,
	0x4d, 0x67, 0xe0, 0x88, 0xdc, 0x0e, 0x9d, 0xc5, 0x8e, 0xc8, 0xe9, 0x2d, 0x4c, 0x4b, 0xa9, 0x85,
	0x11, 0xb2, 0xb0, 0xc3, 0xe1, 0x6a, 0xb2, 0x6c, 0xed, 0xe3, 0xbe, 0x40, 0xe7, 0x10, 0xe4, 0x42,
	0x61, 0x66, 0xbb, 0xdc, 0x71, 0xd7, 0x50, 0xa1, 0x14, 0xbc, 0x3c, 0x35, 0x29, 0xf3, 0x22, 0xb2,
	0x08, 0x62, 0x7b, 0xe6, 0x1a, 0x42, 0x5d, 0xa6, 0x19, 0x26, 0x58, 0x18, 0x54, 0x94, 0xc1, 0xc4,
	0xca, 0x97, 0xa7, 0x1f, 0x86, 0x4e, 0xfe, 0x27, 0x08, 0xbf, 0x83, 0xcb, 0x83, 0xa5, 0x89, 0x42,
	0x43, 0x6f, 0x60, 0x8a, 0x36, 0x81, 0x7e, 0x73, 0xaf, 0xf9, 0x17, 0x01, 0x68, 0xfb, 0xdf, 0xe5,
	0x27, 0xfe, 0xc1, 0x78, 0x68, 0xe2, 0x8c, 0x4d, 0x46, 0xfc, 0xee, 0x51, 0xfc, 0xde, 0xaf, 0xfc,
	0x57, 0x30, 0x1b, 0x78, 0x1a, 0x7c, 0xfe, 0xd8, 0xc5, 0xf8, 0x86, 0xe9, 0xa9, 0x88, 0xfc, 0xba,
	0x8b, 0xc5, 0x9a, 0x58, 0xdf, 0x07, 0x08, 0xb6, 0x68, 0x12, 0x6d, 0x52, 0x73, 0xaa, 0xeb, 0x3d,
	0x5c, 0xf4, 0x16, 0x36, 0xea, 0x39, 0x04, 0x05, 0x8a, 0xed, 0x6e, 0x23, 0x95, 0x66, 0x24, 0x72,
	0xed, 0x25, 0xdb, 0xe7, 0x17, 0x0f, 0x15, 0xbe, 0xee, 0x42, 0x2f, 0x3f, 0xf4, 0xee, 0xc8, 0xa1,
	0x8d, 0x6f, 0xff, 0xc0, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x2d, 0x93, 0xf5, 0x12, 0x03,
	0x00, 0x00,
}
