// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: passport_model.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type User struct {
	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" gorm:"AUTO_INCREMENT"`
	Username   string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" bson:"username" rorm:"uname"  unique:"true"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" bson:"password" rorm:"pwd"`
	Salt       string `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty" bson:"salt" rorm:"salt"`
	Channeluid string `protobuf:"bytes,5,opt,name=channeluid,proto3" json:"channeluid,omitempty" bson:"cuid" rorm:"cuid"`
	Channel    string `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty" bson:"channel" rorm:"channel"`
	Avatar     string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty" bson:"avatar" rorm:"avatar"`
	Mobile     string `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty" bson:"mobile"`
	Openid     string `protobuf:"bytes,9,opt,name=openid,proto3" json:"openid,omitempty" bson:"openid"`
	Ip         string `protobuf:"bytes,10,opt,name=ip,proto3" json:"ip,omitempty" bson:"ip"`
	Status     int32  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty" bson:"status" rorm:"status"`
	RegTime    int64  `protobuf:"varint,12,opt,name=regTime,proto3" json:"regTime,omitempty" bson:"regtime"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptorPassportModel, []int{0} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *User) GetChanneluid() string {
	if m != nil {
		return m.Channeluid
	}
	return ""
}

func (m *User) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *User) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *User) GetRegTime() int64 {
	if m != nil {
		return m.RegTime
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "protocol.User")
}
func (m *User) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *User) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(m.Id))
	}
	if len(m.Username) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Username)))
		i += copy(dAtA[i:], m.Username)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	if len(m.Salt) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Salt)))
		i += copy(dAtA[i:], m.Salt)
	}
	if len(m.Channeluid) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Channeluid)))
		i += copy(dAtA[i:], m.Channeluid)
	}
	if len(m.Channel) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Channel)))
		i += copy(dAtA[i:], m.Channel)
	}
	if len(m.Avatar) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Avatar)))
		i += copy(dAtA[i:], m.Avatar)
	}
	if len(m.Mobile) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Mobile)))
		i += copy(dAtA[i:], m.Mobile)
	}
	if len(m.Openid) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Openid)))
		i += copy(dAtA[i:], m.Openid)
	}
	if len(m.Ip) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if m.Status != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(m.Status))
	}
	if m.RegTime != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintPassportModel(dAtA, i, uint64(m.RegTime))
	}
	return i, nil
}

func encodeVarintPassportModel(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *User) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPassportModel(uint64(m.Id))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Channeluid)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Mobile)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Openid)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovPassportModel(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovPassportModel(uint64(m.Status))
	}
	if m.RegTime != 0 {
		n += 1 + sovPassportModel(uint64(m.RegTime))
	}
	return n
}

func sovPassportModel(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPassportModel(x uint64) (n int) {
	return sovPassportModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *User) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPassportModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: User: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: User: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channeluid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channeluid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mobile", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mobile = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Openid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Openid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPassportModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegTime", wireType)
			}
			m.RegTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPassportModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPassportModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPassportModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPassportModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPassportModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPassportModel
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPassportModel
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPassportModel(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPassportModel = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPassportModel   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("passport_model.proto", fileDescriptorPassportModel) }

var fileDescriptorPassportModel = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4d, 0x6e, 0xd4, 0x30,
	0x14, 0xc7, 0xc9, 0x74, 0x3e, 0x0d, 0x45, 0x60, 0x21, 0x61, 0xb5, 0x6a, 0x1c, 0x2c, 0x16, 0x83,
	0x80, 0xce, 0x02, 0x24, 0xa4, 0xe9, 0x8a, 0x41, 0x5d, 0x20, 0x44, 0x91, 0xac, 0xe9, 0x7a, 0x94,
	0x0f, 0x93, 0x5a, 0x4a, 0xe2, 0xe0, 0xd8, 0xf4, 0x04, 0xdc, 0x81, 0x23, 0xb1, 0xe4, 0x04, 0x16,
	0x1a, 0x6e, 0xe0, 0x13, 0x54, 0xb1, 0x93, 0xa8, 0x9a, 0xd5, 0xbc, 0xff, 0x7b, 0xbf, 0xdf, 0x1b,
	0x27, 0x31, 0x78, 0x56, 0xc7, 0x4d, 0x53, 0x0b, 0xa9, 0x76, 0xa5, 0xc8, 0x58, 0x71, 0x5e, 0x4b,
	0xa1, 0x04, 0x9c, 0xbb, 0x9f, 0x54, 0x14, 0x27, 0x6f, 0x73, 0xae, 0x6e, 0x74, 0x72, 0x9e, 0x8a,
	0x72, 0x95, 0x8b, 0x5c, 0xac, 0xdc, 0x24, 0xd1, 0xdf, 0x5d, 0x72, 0xc1, 0x55, 0x5e, 0x24, 0xbf,
	0x26, 0x60, 0x7c, 0xdd, 0x30, 0x09, 0xdf, 0x83, 0x11, 0xcf, 0x50, 0x10, 0x05, 0xcb, 0xa3, 0xcd,
	0x4b, 0x6b, 0x70, 0x94, 0x34, 0xa2, 0x5a, 0x93, 0x1d, 0xcf, 0x48, 0x94, 0x0b, 0x59, 0xae, 0xc9,
	0xc7, 0xeb, 0xed, 0xb7, 0xdd, 0xe7, 0xab, 0x4f, 0xf4, 0xf2, 0xeb, 0xe5, 0xd5, 0x96, 0xd0, 0x11,
	0xcf, 0xe0, 0x17, 0x30, 0xd7, 0x0d, 0x93, 0x55, 0x5c, 0x32, 0x34, 0x8a, 0x82, 0xe5, 0x62, 0xb3,
	0xb2, 0x06, 0xbf, 0xf6, 0x6e, 0x3f, 0x21, 0x91, 0x74, 0x0b, 0xb4, 0x0f, 0x91, 0xae, 0xf8, 0x0f,
	0xcd, 0xd6, 0x44, 0x49, 0xcd, 0x08, 0x1d, 0x16, 0xc0, 0x35, 0x98, 0xb7, 0x0f, 0x77, 0x2b, 0x64,
	0x86, 0x8e, 0xdc, 0xb2, 0xd0, 0x1a, 0x7c, 0xe2, 0x97, 0xf5, 0x93, 0x7e, 0x59, 0x7d, 0x9b, 0x11,
	0x3a, 0xf0, 0x70, 0x05, 0xc6, 0x4d, 0x5c, 0x28, 0x34, 0x76, 0xde, 0xa9, 0x35, 0xf8, 0xb9, 0xf7,
	0xda, 0x6e, 0xef, 0xb8, 0x9a, 0x3a, 0x10, 0x5e, 0x00, 0x90, 0xde, 0xc4, 0x55, 0xc5, 0x0a, 0xcd,
	0x33, 0x34, 0x39, 0xd4, 0x52, 0xcd, 0x87, 0xbf, 0x72, 0x35, 0xbd, 0x87, 0xc3, 0x0b, 0x30, 0xeb,
	0x12, 0x9a, 0x3a, 0xf3, 0x85, 0x35, 0xf8, 0xac, 0x33, 0xfd, 0x60, 0x90, 0xbb, 0x48, 0x7b, 0x03,
	0x7e, 0x00, 0xd3, 0xf8, 0x67, 0xac, 0x62, 0x89, 0x66, 0xce, 0xc5, 0xd6, 0xe0, 0x53, 0xef, 0xfa,
	0x7e, 0xaf, 0x76, 0x89, 0x76, 0x38, 0x7c, 0x05, 0xa6, 0xa5, 0x48, 0x78, 0xc1, 0xd0, 0xdc, 0x89,
	0x4f, 0xad, 0xc1, 0xc7, 0x5e, 0xf4, 0x7d, 0x42, 0x3b, 0xa0, 0x45, 0x45, 0xcd, 0x2a, 0x9e, 0xa1,
	0xc5, 0x21, 0xea, 0xfb, 0x84, 0x76, 0x00, 0x3c, 0x03, 0x23, 0x5e, 0x23, 0xe0, 0xb0, 0x63, 0x6b,
	0xf0, 0xc2, 0x63, 0xbc, 0x6e, 0xbf, 0x70, 0xdd, 0x9e, 0xb6, 0x51, 0xb1, 0xd2, 0x0d, 0x7a, 0x18,
	0x05, 0xcb, 0xc9, 0xfd, 0xd3, 0xfa, 0xfe, 0xf0, 0x72, 0x7d, 0xa2, 0x1d, 0x0e, 0xdf, 0x80, 0x99,
	0x64, 0xf9, 0x96, 0x97, 0x0c, 0x3d, 0x72, 0xb7, 0x0a, 0x5a, 0x83, 0x1f, 0x7b, 0x53, 0xb2, 0x5c,
	0xf1, 0x92, 0x11, 0xda, 0x23, 0x9b, 0x27, 0x7f, 0xf6, 0x61, 0xf0, 0x77, 0x1f, 0x06, 0xff, 0xf6,
	0x61, 0xf0, 0xfb, 0x7f, 0xf8, 0x20, 0x99, 0xba, 0x0b, 0xfa, 0xee, 0x2e, 0x00, 0x00, 0xff, 0xff,
	0x6a, 0xbb, 0x5a, 0xb0, 0xf1, 0x02, 0x00, 0x00,
}
