// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocol.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// request
type Request struct {
	Session int32 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	// 1
	//
	// Types that are valid to be assigned to Passport:
	//	*Request_LoginRegister
	//	*Request_LoginLogin
	//	*Request_TokenLogin
	Passport isRequest_Passport `protobuf_oneof:"passport"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptorProtocol, []int{0} }

type isRequest_Passport interface {
	isRequest_Passport()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Request_LoginRegister struct {
	LoginRegister *LoginRegister `protobuf:"bytes,6,opt,name=loginRegister,oneof"`
}
type Request_LoginLogin struct {
	LoginLogin *LoginLogin `protobuf:"bytes,7,opt,name=loginLogin,oneof"`
}
type Request_TokenLogin struct {
	TokenLogin *TokenLogin `protobuf:"bytes,8,opt,name=tokenLogin,oneof"`
}

func (*Request_LoginRegister) isRequest_Passport() {}
func (*Request_LoginLogin) isRequest_Passport()    {}
func (*Request_TokenLogin) isRequest_Passport()    {}

func (m *Request) GetPassport() isRequest_Passport {
	if m != nil {
		return m.Passport
	}
	return nil
}

func (m *Request) GetSession() int32 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *Request) GetLoginRegister() *LoginRegister {
	if x, ok := m.GetPassport().(*Request_LoginRegister); ok {
		return x.LoginRegister
	}
	return nil
}

func (m *Request) GetLoginLogin() *LoginLogin {
	if x, ok := m.GetPassport().(*Request_LoginLogin); ok {
		return x.LoginLogin
	}
	return nil
}

func (m *Request) GetTokenLogin() *TokenLogin {
	if x, ok := m.GetPassport().(*Request_TokenLogin); ok {
		return x.TokenLogin
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_LoginRegister)(nil),
		(*Request_LoginLogin)(nil),
		(*Request_TokenLogin)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// passport
	switch x := m.Passport.(type) {
	case *Request_LoginRegister:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginRegister); err != nil {
			return err
		}
	case *Request_LoginLogin:
		_ = b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginLogin); err != nil {
			return err
		}
	case *Request_TokenLogin:
		_ = b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TokenLogin); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Passport has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 6: // passport.loginRegister
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginRegister)
		err := b.DecodeMessage(msg)
		m.Passport = &Request_LoginRegister{msg}
		return true, err
	case 7: // passport.loginLogin
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginLogin)
		err := b.DecodeMessage(msg)
		m.Passport = &Request_LoginLogin{msg}
		return true, err
	case 8: // passport.tokenLogin
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TokenLogin)
		err := b.DecodeMessage(msg)
		m.Passport = &Request_TokenLogin{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// passport
	switch x := m.Passport.(type) {
	case *Request_LoginRegister:
		s := proto.Size(x.LoginRegister)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_LoginLogin:
		s := proto.Size(x.LoginLogin)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_TokenLogin:
		s := proto.Size(x.TokenLogin)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// response
type Response struct {
	Session int32 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Code    Code  `protobuf:"varint,2,opt,name=code,proto3,enum=protocol.Code" json:"code,omitempty"`
	// 2
	//
	// Types that are valid to be assigned to Passport:
	//	*Response_LoginRegisterRet
	//	*Response_LoginLoginRet
	//	*Response_TokenLoginRet
	Passport isResponse_Passport `protobuf_oneof:"passport"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorProtocol, []int{1} }

type isResponse_Passport interface {
	isResponse_Passport()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Response_LoginRegisterRet struct {
	LoginRegisterRet *LoginRegisterRet `protobuf:"bytes,6,opt,name=loginRegisterRet,oneof"`
}
type Response_LoginLoginRet struct {
	LoginLoginRet *LoginLoginRet `protobuf:"bytes,7,opt,name=loginLoginRet,oneof"`
}
type Response_TokenLoginRet struct {
	TokenLoginRet *TokenLoginRet `protobuf:"bytes,8,opt,name=tokenLoginRet,oneof"`
}

func (*Response_LoginRegisterRet) isResponse_Passport() {}
func (*Response_LoginLoginRet) isResponse_Passport()    {}
func (*Response_TokenLoginRet) isResponse_Passport()    {}

func (m *Response) GetPassport() isResponse_Passport {
	if m != nil {
		return m.Passport
	}
	return nil
}

func (m *Response) GetSession() int32 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *Response) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *Response) GetLoginRegisterRet() *LoginRegisterRet {
	if x, ok := m.GetPassport().(*Response_LoginRegisterRet); ok {
		return x.LoginRegisterRet
	}
	return nil
}

func (m *Response) GetLoginLoginRet() *LoginLoginRet {
	if x, ok := m.GetPassport().(*Response_LoginLoginRet); ok {
		return x.LoginLoginRet
	}
	return nil
}

func (m *Response) GetTokenLoginRet() *TokenLoginRet {
	if x, ok := m.GetPassport().(*Response_TokenLoginRet); ok {
		return x.TokenLoginRet
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_LoginRegisterRet)(nil),
		(*Response_LoginLoginRet)(nil),
		(*Response_TokenLoginRet)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// passport
	switch x := m.Passport.(type) {
	case *Response_LoginRegisterRet:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginRegisterRet); err != nil {
			return err
		}
	case *Response_LoginLoginRet:
		_ = b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginLoginRet); err != nil {
			return err
		}
	case *Response_TokenLoginRet:
		_ = b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TokenLoginRet); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Passport has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 6: // passport.loginRegisterRet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginRegisterRet)
		err := b.DecodeMessage(msg)
		m.Passport = &Response_LoginRegisterRet{msg}
		return true, err
	case 7: // passport.loginLoginRet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginLoginRet)
		err := b.DecodeMessage(msg)
		m.Passport = &Response_LoginLoginRet{msg}
		return true, err
	case 8: // passport.tokenLoginRet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TokenLoginRet)
		err := b.DecodeMessage(msg)
		m.Passport = &Response_TokenLoginRet{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// passport
	switch x := m.Passport.(type) {
	case *Response_LoginRegisterRet:
		s := proto.Size(x.LoginRegisterRet)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_LoginLoginRet:
		s := proto.Size(x.LoginLoginRet)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_TokenLoginRet:
		s := proto.Size(x.TokenLoginRet)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Push struct {
}

func (m *Push) Reset()                    { *m = Push{} }
func (m *Push) String() string            { return proto.CompactTextString(m) }
func (*Push) ProtoMessage()               {}
func (*Push) Descriptor() ([]byte, []int) { return fileDescriptorProtocol, []int{2} }

func init() {
	proto.RegisterType((*Request)(nil), "protocol.Request")
	proto.RegisterType((*Response)(nil), "protocol.Response")
	proto.RegisterType((*Push)(nil), "protocol.Push")
}
func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Session != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.Session))
	}
	if m.Passport != nil {
		nn1, err := m.Passport.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn1
	}
	return i, nil
}

func (m *Request_LoginRegister) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.LoginRegister != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.LoginRegister.Size()))
		n2, err := m.LoginRegister.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}
func (m *Request_LoginLogin) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.LoginLogin != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.LoginLogin.Size()))
		n3, err := m.LoginLogin.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}
func (m *Request_TokenLogin) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.TokenLogin != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.TokenLogin.Size()))
		n4, err := m.TokenLogin.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}
func (m *Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Session != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.Session))
	}
	if m.Code != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.Code))
	}
	if m.Passport != nil {
		nn5, err := m.Passport.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn5
	}
	return i, nil
}

func (m *Response_LoginRegisterRet) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.LoginRegisterRet != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.LoginRegisterRet.Size()))
		n6, err := m.LoginRegisterRet.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}
func (m *Response_LoginLoginRet) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.LoginLoginRet != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.LoginLoginRet.Size()))
		n7, err := m.LoginLoginRet.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}
func (m *Response_TokenLoginRet) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.TokenLoginRet != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.TokenLoginRet.Size()))
		n8, err := m.TokenLoginRet.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}
func (m *Push) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Push) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeVarintProtocol(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Request) Size() (n int) {
	var l int
	_ = l
	if m.Session != 0 {
		n += 1 + sovProtocol(uint64(m.Session))
	}
	if m.Passport != nil {
		n += m.Passport.Size()
	}
	return n
}

func (m *Request_LoginRegister) Size() (n int) {
	var l int
	_ = l
	if m.LoginRegister != nil {
		l = m.LoginRegister.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Request_LoginLogin) Size() (n int) {
	var l int
	_ = l
	if m.LoginLogin != nil {
		l = m.LoginLogin.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Request_TokenLogin) Size() (n int) {
	var l int
	_ = l
	if m.TokenLogin != nil {
		l = m.TokenLogin.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Response) Size() (n int) {
	var l int
	_ = l
	if m.Session != 0 {
		n += 1 + sovProtocol(uint64(m.Session))
	}
	if m.Code != 0 {
		n += 1 + sovProtocol(uint64(m.Code))
	}
	if m.Passport != nil {
		n += m.Passport.Size()
	}
	return n
}

func (m *Response_LoginRegisterRet) Size() (n int) {
	var l int
	_ = l
	if m.LoginRegisterRet != nil {
		l = m.LoginRegisterRet.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Response_LoginLoginRet) Size() (n int) {
	var l int
	_ = l
	if m.LoginLoginRet != nil {
		l = m.LoginLoginRet.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Response_TokenLoginRet) Size() (n int) {
	var l int
	_ = l
	if m.TokenLoginRet != nil {
		l = m.TokenLoginRet.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Push) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovProtocol(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozProtocol(x uint64) (n int) {
	return sovProtocol(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtocol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			m.Session = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Session |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoginRegister", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LoginRegister{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Passport = &Request_LoginRegister{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoginLogin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LoginLogin{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Passport = &Request_LoginLogin{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenLogin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TokenLogin{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Passport = &Request_TokenLogin{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtocol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtocol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtocol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			m.Session = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Session |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoginRegisterRet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LoginRegisterRet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Passport = &Response_LoginRegisterRet{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoginLoginRet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LoginLoginRet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Passport = &Response_LoginLoginRet{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenLoginRet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TokenLoginRet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Passport = &Response_TokenLoginRet{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtocol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtocol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Push) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtocol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Push: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Push: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipProtocol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtocol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProtocol(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProtocol
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthProtocol
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowProtocol
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipProtocol(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthProtocol = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProtocol   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("protocol.proto", fileDescriptorProtocol) }

var fileDescriptorProtocol = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4a, 0xf4, 0x30,
	0x18, 0xc6, 0x9b, 0x61, 0xbe, 0x69, 0x79, 0x3f, 0x2c, 0x25, 0x20, 0xc4, 0x41, 0x4a, 0xe9, 0xaa,
	0xab, 0x59, 0x8c, 0x0b, 0xb7, 0x3a, 0x6e, 0x8a, 0xcc, 0x42, 0x72, 0x81, 0x41, 0x67, 0x5e, 0xc6,
	0x62, 0x69, 0x6a, 0x92, 0xde, 0xc5, 0x13, 0x78, 0x16, 0x97, 0x1e, 0x41, 0x3a, 0x17, 0x91, 0xa6,
	0xa9, 0x9d, 0xd6, 0x3f, 0x9b, 0x90, 0xe4, 0xc9, 0xef, 0x09, 0xef, 0x0f, 0xfc, 0x52, 0x0a, 0x2d,
	0xb6, 0x22, 0x5f, 0x98, 0x0d, 0xf5, 0xba, 0xf3, 0xdc, 0x2f, 0xef, 0x95, 0x2a, 0x85, 0xd4, 0x6d,
	0x32, 0x0f, 0x24, 0xaa, 0x2a, 0xd7, 0x5b, 0xb1, 0xc3, 0xf6, 0x26, 0x3e, 0x10, 0x70, 0x39, 0x3e,
	0x57, 0xa8, 0x34, 0x65, 0xe0, 0x2a, 0x54, 0x2a, 0x13, 0x05, 0x23, 0x11, 0x49, 0xfe, 0xf1, 0xee,
	0x48, 0xaf, 0xe0, 0x24, 0x17, 0xfb, 0xac, 0xe0, 0xb8, 0xcf, 0x94, 0x46, 0xc9, 0x66, 0x11, 0x49,
	0xfe, 0x2f, 0xd9, 0xe2, 0xeb, 0x67, 0x13, 0x6f, 0xa4, 0xcd, 0x53, 0x87, 0x0f, 0x01, 0x7a, 0x09,
	0x60, 0x2e, 0xd6, 0xcd, 0xc2, 0x5c, 0x83, 0x9f, 0x8e, 0x71, 0xb3, 0xa6, 0x0e, 0x3f, 0x7a, 0xda,
	0x80, 0x5a, 0x3c, 0xa1, 0x05, 0xbd, 0x31, 0x68, 0xb2, 0x1e, 0xec, 0x9f, 0xae, 0x00, 0xbc, 0x6e,
	0xfa, 0xf8, 0x75, 0x02, 0x1e, 0x47, 0x55, 0x8a, 0x42, 0xe1, 0x1f, 0x63, 0xc6, 0x30, 0x6d, 0xd4,
	0xb0, 0x49, 0x44, 0x12, 0x7f, 0xe9, 0xf7, 0xbf, 0xdc, 0x88, 0x1d, 0x72, 0x93, 0xd1, 0x5b, 0x08,
	0x06, 0x93, 0x71, 0xd4, 0xd6, 0xc6, 0xf9, 0x6f, 0x36, 0x36, 0x12, 0x75, 0xea, 0xf0, 0x6f, 0x1c,
	0xbd, 0xb6, 0x5a, 0xd7, 0x6d, 0xa0, 0xad, 0x97, 0xb3, 0x1f, 0xbd, 0xd8, 0x96, 0x21, 0xd1, 0x54,
	0xf4, 0x33, 0x37, 0x15, 0xde, 0xb8, 0xe2, 0xc8, 0x50, 0x57, 0x31, 0x20, 0x06, 0xa2, 0x66, 0x30,
	0xbd, 0xab, 0xd4, 0xe3, 0x2a, 0x78, 0xab, 0x43, 0xf2, 0x5e, 0x87, 0xe4, 0xa3, 0x0e, 0xc9, 0xcb,
	0x21, 0x74, 0x1e, 0x66, 0xa6, 0xf0, 0xe2, 0x33, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x07, 0xe5, 0x50,
	0x6d, 0x02, 0x00, 0x00,
}
