// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocol.proto

package game

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// request
type Request struct {
	Session int32 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	// -----------------游戏模块接口---------------
	//
	// Types that are valid to be assigned to Request:
	//	*Request_GetUserInfo
	//	*Request_LoginRole
	//	*Request_CreateRole
	//	*Request_RemoveRole
	Request isRequest_Request `protobuf_oneof:"request"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptorProtocol, []int{0} }

type isRequest_Request interface {
	isRequest_Request()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Request_GetUserInfo struct {
	GetUserInfo *GetUserInfo `protobuf:"bytes,3,opt,name=getUserInfo,oneof"`
}
type Request_LoginRole struct {
	LoginRole *LoginRole `protobuf:"bytes,4,opt,name=loginRole,oneof"`
}
type Request_CreateRole struct {
	CreateRole *CreateRole `protobuf:"bytes,5,opt,name=createRole,oneof"`
}
type Request_RemoveRole struct {
	RemoveRole *RemoveRole `protobuf:"bytes,6,opt,name=removeRole,oneof"`
}

func (*Request_GetUserInfo) isRequest_Request() {}
func (*Request_LoginRole) isRequest_Request()   {}
func (*Request_CreateRole) isRequest_Request()  {}
func (*Request_RemoveRole) isRequest_Request()  {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetSession() int32 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *Request) GetGetUserInfo() *GetUserInfo {
	if x, ok := m.GetRequest().(*Request_GetUserInfo); ok {
		return x.GetUserInfo
	}
	return nil
}

func (m *Request) GetLoginRole() *LoginRole {
	if x, ok := m.GetRequest().(*Request_LoginRole); ok {
		return x.LoginRole
	}
	return nil
}

func (m *Request) GetCreateRole() *CreateRole {
	if x, ok := m.GetRequest().(*Request_CreateRole); ok {
		return x.CreateRole
	}
	return nil
}

func (m *Request) GetRemoveRole() *RemoveRole {
	if x, ok := m.GetRequest().(*Request_RemoveRole); ok {
		return x.RemoveRole
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_GetUserInfo)(nil),
		(*Request_LoginRole)(nil),
		(*Request_CreateRole)(nil),
		(*Request_RemoveRole)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// request
	switch x := m.Request.(type) {
	case *Request_GetUserInfo:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetUserInfo); err != nil {
			return err
		}
	case *Request_LoginRole:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginRole); err != nil {
			return err
		}
	case *Request_CreateRole:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateRole); err != nil {
			return err
		}
	case *Request_RemoveRole:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoveRole); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Request has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 3: // request.getUserInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetUserInfo)
		err := b.DecodeMessage(msg)
		m.Request = &Request_GetUserInfo{msg}
		return true, err
	case 4: // request.loginRole
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginRole)
		err := b.DecodeMessage(msg)
		m.Request = &Request_LoginRole{msg}
		return true, err
	case 5: // request.createRole
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateRole)
		err := b.DecodeMessage(msg)
		m.Request = &Request_CreateRole{msg}
		return true, err
	case 6: // request.removeRole
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveRole)
		err := b.DecodeMessage(msg)
		m.Request = &Request_RemoveRole{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// request
	switch x := m.Request.(type) {
	case *Request_GetUserInfo:
		s := proto.Size(x.GetUserInfo)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_LoginRole:
		s := proto.Size(x.LoginRole)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_CreateRole:
		s := proto.Size(x.CreateRole)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_RemoveRole:
		s := proto.Size(x.RemoveRole)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// response
type Response struct {
	Session int32 `protobuf:"varint,1,opt,name=session,proto3" json:"session,omitempty"`
	Code    Code  `protobuf:"varint,2,opt,name=code,proto3,enum=game.Code" json:"code,omitempty"`
	// -----------------游戏模块接口---------------
	//
	// Types that are valid to be assigned to Response:
	//	*Response_GetUserInfoRet
	//	*Response_LoginRoleRet
	//	*Response_CreateRoleRet
	//	*Response_RemoveRoleRet
	Response isResponse_Response `protobuf_oneof:"response"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptorProtocol, []int{1} }

type isResponse_Response interface {
	isResponse_Response()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Response_GetUserInfoRet struct {
	GetUserInfoRet *GetUserInfoRet `protobuf:"bytes,3,opt,name=getUserInfoRet,oneof"`
}
type Response_LoginRoleRet struct {
	LoginRoleRet *LoginRoleRet `protobuf:"bytes,4,opt,name=loginRoleRet,oneof"`
}
type Response_CreateRoleRet struct {
	CreateRoleRet *CreateRoleRet `protobuf:"bytes,5,opt,name=createRoleRet,oneof"`
}
type Response_RemoveRoleRet struct {
	RemoveRoleRet *RemoveRoleRet `protobuf:"bytes,6,opt,name=removeRoleRet,oneof"`
}

func (*Response_GetUserInfoRet) isResponse_Response() {}
func (*Response_LoginRoleRet) isResponse_Response()   {}
func (*Response_CreateRoleRet) isResponse_Response()  {}
func (*Response_RemoveRoleRet) isResponse_Response()  {}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetSession() int32 {
	if m != nil {
		return m.Session
	}
	return 0
}

func (m *Response) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *Response) GetGetUserInfoRet() *GetUserInfoRet {
	if x, ok := m.GetResponse().(*Response_GetUserInfoRet); ok {
		return x.GetUserInfoRet
	}
	return nil
}

func (m *Response) GetLoginRoleRet() *LoginRoleRet {
	if x, ok := m.GetResponse().(*Response_LoginRoleRet); ok {
		return x.LoginRoleRet
	}
	return nil
}

func (m *Response) GetCreateRoleRet() *CreateRoleRet {
	if x, ok := m.GetResponse().(*Response_CreateRoleRet); ok {
		return x.CreateRoleRet
	}
	return nil
}

func (m *Response) GetRemoveRoleRet() *RemoveRoleRet {
	if x, ok := m.GetResponse().(*Response_RemoveRoleRet); ok {
		return x.RemoveRoleRet
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_GetUserInfoRet)(nil),
		(*Response_LoginRoleRet)(nil),
		(*Response_CreateRoleRet)(nil),
		(*Response_RemoveRoleRet)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// response
	switch x := m.Response.(type) {
	case *Response_GetUserInfoRet:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetUserInfoRet); err != nil {
			return err
		}
	case *Response_LoginRoleRet:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginRoleRet); err != nil {
			return err
		}
	case *Response_CreateRoleRet:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateRoleRet); err != nil {
			return err
		}
	case *Response_RemoveRoleRet:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoveRoleRet); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Response has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 3: // response.getUserInfoRet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetUserInfoRet)
		err := b.DecodeMessage(msg)
		m.Response = &Response_GetUserInfoRet{msg}
		return true, err
	case 4: // response.loginRoleRet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginRoleRet)
		err := b.DecodeMessage(msg)
		m.Response = &Response_LoginRoleRet{msg}
		return true, err
	case 5: // response.createRoleRet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateRoleRet)
		err := b.DecodeMessage(msg)
		m.Response = &Response_CreateRoleRet{msg}
		return true, err
	case 6: // response.removeRoleRet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RemoveRoleRet)
		err := b.DecodeMessage(msg)
		m.Response = &Response_RemoveRoleRet{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// response
	switch x := m.Response.(type) {
	case *Response_GetUserInfoRet:
		s := proto.Size(x.GetUserInfoRet)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_LoginRoleRet:
		s := proto.Size(x.LoginRoleRet)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_CreateRoleRet:
		s := proto.Size(x.CreateRoleRet)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_RemoveRoleRet:
		s := proto.Size(x.RemoveRoleRet)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Request)(nil), "game.Request")
	proto.RegisterType((*Response)(nil), "game.Response")
}
func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Session != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.Session))
	}
	if m.Request != nil {
		nn1, err := m.Request.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn1
	}
	return i, nil
}

func (m *Request_GetUserInfo) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.GetUserInfo != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.GetUserInfo.Size()))
		n2, err := m.GetUserInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}
func (m *Request_LoginRole) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.LoginRole != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.LoginRole.Size()))
		n3, err := m.LoginRole.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}
func (m *Request_CreateRole) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CreateRole != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.CreateRole.Size()))
		n4, err := m.CreateRole.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}
func (m *Request_RemoveRole) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.RemoveRole != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.RemoveRole.Size()))
		n5, err := m.RemoveRole.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}
func (m *Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Session != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.Session))
	}
	if m.Code != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.Code))
	}
	if m.Response != nil {
		nn6, err := m.Response.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn6
	}
	return i, nil
}

func (m *Response_GetUserInfoRet) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.GetUserInfoRet != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.GetUserInfoRet.Size()))
		n7, err := m.GetUserInfoRet.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}
func (m *Response_LoginRoleRet) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.LoginRoleRet != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.LoginRoleRet.Size()))
		n8, err := m.LoginRoleRet.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}
func (m *Response_CreateRoleRet) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CreateRoleRet != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.CreateRoleRet.Size()))
		n9, err := m.CreateRoleRet.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	return i, nil
}
func (m *Response_RemoveRoleRet) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.RemoveRoleRet != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintProtocol(dAtA, i, uint64(m.RemoveRoleRet.Size()))
		n10, err := m.RemoveRoleRet.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	return i, nil
}
func encodeVarintProtocol(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Request) Size() (n int) {
	var l int
	_ = l
	if m.Session != 0 {
		n += 1 + sovProtocol(uint64(m.Session))
	}
	if m.Request != nil {
		n += m.Request.Size()
	}
	return n
}

func (m *Request_GetUserInfo) Size() (n int) {
	var l int
	_ = l
	if m.GetUserInfo != nil {
		l = m.GetUserInfo.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Request_LoginRole) Size() (n int) {
	var l int
	_ = l
	if m.LoginRole != nil {
		l = m.LoginRole.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Request_CreateRole) Size() (n int) {
	var l int
	_ = l
	if m.CreateRole != nil {
		l = m.CreateRole.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Request_RemoveRole) Size() (n int) {
	var l int
	_ = l
	if m.RemoveRole != nil {
		l = m.RemoveRole.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Response) Size() (n int) {
	var l int
	_ = l
	if m.Session != 0 {
		n += 1 + sovProtocol(uint64(m.Session))
	}
	if m.Code != 0 {
		n += 1 + sovProtocol(uint64(m.Code))
	}
	if m.Response != nil {
		n += m.Response.Size()
	}
	return n
}

func (m *Response_GetUserInfoRet) Size() (n int) {
	var l int
	_ = l
	if m.GetUserInfoRet != nil {
		l = m.GetUserInfoRet.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Response_LoginRoleRet) Size() (n int) {
	var l int
	_ = l
	if m.LoginRoleRet != nil {
		l = m.LoginRoleRet.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Response_CreateRoleRet) Size() (n int) {
	var l int
	_ = l
	if m.CreateRoleRet != nil {
		l = m.CreateRoleRet.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}
func (m *Response_RemoveRoleRet) Size() (n int) {
	var l int
	_ = l
	if m.RemoveRoleRet != nil {
		l = m.RemoveRoleRet.Size()
		n += 1 + l + sovProtocol(uint64(l))
	}
	return n
}

func sovProtocol(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozProtocol(x uint64) (n int) {
	return sovProtocol(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Request) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtocol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			m.Session = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Session |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetUserInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GetUserInfo{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &Request_GetUserInfo{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoginRole", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LoginRole{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &Request_LoginRole{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateRole", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CreateRole{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &Request_CreateRole{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveRole", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RemoveRole{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &Request_RemoveRole{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtocol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtocol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtocol
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			m.Session = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Session |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetUserInfoRet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GetUserInfoRet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &Response_GetUserInfoRet{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoginRoleRet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &LoginRoleRet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &Response_LoginRoleRet{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateRoleRet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CreateRoleRet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &Response_CreateRoleRet{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveRoleRet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProtocol
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &RemoveRoleRet{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &Response_RemoveRoleRet{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProtocol(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProtocol
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProtocol(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProtocol
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtocol
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthProtocol
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowProtocol
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipProtocol(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthProtocol = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProtocol   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("protocol.proto", fileDescriptorProtocol) }

var fileDescriptorProtocol = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4e, 0xc2, 0x40,
	0x14, 0xc6, 0x3b, 0xc8, 0xdf, 0x87, 0x12, 0x1c, 0x35, 0x36, 0x2c, 0x1a, 0xc2, 0x8a, 0x15, 0x31,
	0xb0, 0x30, 0x31, 0x71, 0x21, 0x6e, 0x70, 0x3b, 0x89, 0xeb, 0x06, 0xe1, 0xd1, 0x90, 0x94, 0x3e,
	0x9c, 0x19, 0xbc, 0x80, 0x97, 0xf0, 0x48, 0x6e, 0x4c, 0x3c, 0x82, 0xc1, 0x8b, 0x98, 0x99, 0x29,
	0xb4, 0x45, 0xe3, 0xae, 0xfd, 0xf2, 0xfd, 0xde, 0xcc, 0xfb, 0x65, 0xa0, 0xb5, 0x96, 0xa4, 0x69,
	0x46, 0xf1, 0xc0, 0x7e, 0xf0, 0x72, 0x34, 0x5d, 0x61, 0x07, 0x24, 0xc5, 0xe8, 0x92, 0x4e, 0x5b,
	0xa2, 0xda, 0xc4, 0x7a, 0x46, 0xf3, 0x34, 0xe9, 0xbd, 0x96, 0xa0, 0x26, 0xf0, 0x79, 0x83, 0x4a,
	0x73, 0x1f, 0x6a, 0x0a, 0x95, 0x5a, 0x52, 0xe2, 0xb3, 0x2e, 0xeb, 0x57, 0xc4, 0xee, 0x97, 0x5f,
	0x43, 0x33, 0x42, 0xfd, 0xa8, 0x50, 0x3e, 0x24, 0x0b, 0xf2, 0x8f, 0xba, 0xac, 0xdf, 0x1c, 0x9e,
	0x0d, 0xcc, 0xfc, 0x41, 0x84, 0x3a, 0xdc, 0x28, 0x94, 0xe1, 0x32, 0x59, 0xd0, 0xc4, 0x13, 0xf9,
	0x26, 0xbf, 0x82, 0x46, 0x4c, 0xd1, 0x32, 0x11, 0x14, 0xa3, 0x5f, 0xb6, 0x58, 0xdb, 0x61, 0x36,
	0x0e, 0xcd, 0xdd, 0x26, 0x9e, 0xc8, 0x4a, 0x7c, 0x04, 0x30, 0x93, 0x38, 0xd5, 0x68, 0x91, 0x8a,
	0x45, 0x4e, 0x1d, 0xe2, 0xf2, 0x1d, 0x93, 0xab, 0x19, 0x48, 0xe2, 0x8a, 0x5e, 0x1c, 0x54, 0xcd,
	0x43, 0x2e, 0xdf, 0x43, 0x59, 0x6d, 0xdc, 0x80, 0x9a, 0x74, 0x9b, 0xf7, 0x3e, 0x4a, 0x50, 0x17,
	0xa8, 0xd6, 0x94, 0x28, 0xfc, 0x47, 0x43, 0x00, 0x65, 0xa3, 0xce, 0x2f, 0x75, 0x59, 0xbf, 0x35,
	0x04, 0x77, 0xc0, 0x3d, 0xcd, 0x51, 0xd8, 0x9c, 0xdf, 0x41, 0x2b, 0xb7, 0xbc, 0x40, 0x9d, 0x9a,
	0xba, 0xfc, 0xc3, 0x54, 0x28, 0x51, 0x4f, 0x3c, 0x71, 0x00, 0xf0, 0x1b, 0x38, 0xde, 0xbb, 0x30,
	0x03, 0x9c, 0xb3, 0xf3, 0x43, 0x67, 0x29, 0x5d, 0xe8, 0xf2, 0x5b, 0x38, 0xc9, 0x9c, 0x18, 0xd8,
	0xd9, 0xbb, 0xf8, 0x65, 0x2f, 0xa5, 0x8b, 0x6d, 0x83, 0x67, 0x76, 0x0c, 0x5e, 0xcd, 0xe3, 0x39,
	0x8f, 0x3b, 0xbc, 0xd0, 0x1e, 0x03, 0xd4, 0x65, 0xaa, 0x70, 0xdc, 0x7e, 0xdf, 0x06, 0xec, 0x73,
	0x1b, 0xb0, 0xaf, 0x6d, 0xc0, 0xde, 0xbe, 0x03, 0xef, 0xa9, 0x6a, 0x9f, 0xdb, 0xe8, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x25, 0xc3, 0x0f, 0xfd, 0xa4, 0x02, 0x00, 0x00,
}
